### ISSUE TITLE
Web application cannot open

### ISSUE THREAD

**Issue by XiaoxuanLin19** [Jhsmit/PyHDX#247]
Hi, I suddenly lost connection to the web application (both using the link http://pyhdx.jhsmit.org/main and http://pyhdx-beta.jhsmit.org/main) and the web server. Is there something I need to do to fix that? Thank you.

**Comment by Jhsmit** [comment]
Thanks for letting me know. Something went wrong on our server. Both http://pyhdx.jhsmit.org and http://pyhdx-beta.jhsmit.org are now back online. Feel free to open a new issue if you encounter any problems.
