### ISSUE TITLE
web application NOT Found

### ISSUE THREAD

**Issue by jiali0411** [Jhsmit/PyHDX#253]
Dear PyHDX developers, 

I tried to use the web application but when I clicked on the link, it said page not found. 
```
Tunnel pyhdx.jhsmit.org not found

ERR_NGROK_3200
```
Could you point me to the correct HTTP address? 

Thanks,
Jiali

**Comment by Jhsmit** [comment]
Hi Jiali, thanks for letting me know. I've restarted the server and it should be back online now.

By the way, you might be interested to try the new version of PyHDX (beta): http://pyhdx-beta.jhsmit.org/

Jochem
