### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by JZbacklife1** [Jhsmit/PyHDX#292]
i try to install the pyHDX, but it shows

twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
panel 0.13.1 has requirement bokeh<2.5.0,>=2.4.0, but you'll have bokeh 0.13.0 which is incompatible.
panel 0.13.1 has requirement tqdm>=4.48.0, but you'll have tqdm 4.26.0 which is incompatible.
Installing collected packages: typing-extensions, torch, hdxrate, zipp, importlib-metadata, markdown, param, pyct, pyviz-comms, panel, pbr, sympy, toposort, symfit, pyhdx
  Found existing installation: sympy 1.1.1
Cannot uninstall 'sympy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

suggestions? thanks

**Comment by Jhsmit** [comment]
Hi, thanks for reaching out

Are you using a new clean virtual / conda env to install PyHDX in?
Which command are you using to install PyHDX?

**Comment by JZbacklife1** [comment]
hi Jhsmit,
i successfully go through most of the step but not the last one:
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (C:\Users\zj\Anaconda3\lib\site-packages\numpy\lib\arraypad.py)
why it shows up? dont know how to fix this since i want to pop up the web server

thanks

**Comment by Jhsmit** [comment]
Which version of numpy did you install?
There are pinned versions in dev/deps/pinned which should work
There I've used numpy==1.22.3

**Comment by JZbacklife1** [comment]
i think there is no numpy in the dev/deps/pinned folder which only includes py38 windows pip.tex file

so in this case i need to install numpy myself?

thanks

**Comment by JZbacklife1** [comment]
Hi Jhsmit,
pls make the install instructions more clearly and i feel i am a few steps to finishline 

thx

**Comment by Jhsmit** [comment]
I've update the installation documentation (#294) 
There was a duplicate section there causing confusion

Please have a look to see if it helps.

Are you sure you need to install the development version? Otherwise I would recommend installing the stable version, which will be much easier.

**Comment by JZbacklife1** [comment]
hi Jhsmit

it still very confusing since there are some other typo errors like req-base.txt instead of _req-base.txt file name issues as well the location of the files in the folder dir. 
I can go through half of the steps but stop here, any suggestions? 

thanks

(py38_pyhdx) C:\PyHDX\requirements>conda install --file req-base.txt --file req-base.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - hdxrate[version='>=0.2.0,>=0.2.0']
  - omegaconf[version='>=2.2.2,>=2.2.2']
  - symfit[version='>=0.5.5,>=0.5.5']

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



(py38_pyhdx) C:\PyHDX\requirements>cd..

(py38_pyhdx) C:\PyHDX>python pyhdx/web/serve.py
Traceback (most recent call last):
  File "pyhdx/web/serve.py", line 5, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by Jhsmit** [comment]
I can't find any of the typo errors anymore in the lastest version of the docs. 
If you see them please point out exactly where in a separate issue so that i can fix them

with respect to the installation, you need to add conda-forge  as channel to install the dependencies

```
$ conda install --file requirements/req-all.txt -c conda-forge
```
