### ISSUE TITLE
python_requirements.py

### ISSUE THREAD

**Issue by JZbacklife1** [Jhsmit/PyHDX#293]
Generate conda requirements files from setup.cfg:

$ python _requirements.py

hi, i can not find the above file in the PyHDX folder??

pls indicate how to proceed?

thanks

**Comment by Jhsmit** [comment]
Hi, sorry indeed these instructions are not correct

Please skip the `$python _requirements.py` step and proceed to the next step `$conda instlal --file ...`, where the requirement files are in the `dev/deps` folder

Thanks for pointing this out, I'll update the docs soon

**Comment by Jhsmit** [comment]
closed by #294
