### ISSUE TITLE
rfu_residues_sd error 

### ISSUE THREAD

**Issue by tuttlelm** [Jhsmit/PyHDX#348]
I have generated an HDX Measurement object from my data. (Naively) Looking at the code it seems like there should be both a .rfu_residues field and .rfu_residues_sd field for this object, but trying to access hdxm.rfu_residues_sd generates an error (summarized below). The rfu_residues values are generated and are sensible. Is there a way to generate the error bars on the rfu_residues values? 

Thanks for your work on this repository!

```
:
:
File ~/.local/lib/python3.10/site-packages/pyhdx/models.py:625, in HDXTimepoint.rfu_residues_sd(self)
    [621](pyhdx/models.py:621) @property
    [622](pyhdx/models.py:622) def rfu_residues_sd(self) -> pd.Series:
    [623](pyhdx/models.py:623)     """Error propagated standard deviations of RFU per residue."""
--> [625](pyhdx/models.py:625)     return self.propagate_errors("rfu_sd")
:
:
KeyError: 'rfu_sd'
```

**Comment by Jhsmit** [comment]
Hi, thanks for opening the issue

Normally you do have sd values, they are calculated from the sd values associated with the d-uptake values ('uptake_sd'), That typically happens in the `apply_control` function [here](https://github.com/Jhsmit/PyHDX/blob/9abd2c67d74e4e6805f259a4daf41c41756558a6/pyhdx/process.py#L62)

Depending on how you've created the `HDXMeasurement` object, you might not have this field. 
This template shows the typical steps: https://github.com/Jhsmit/PyHDX/blob/master/templates/01_load_secb_data.py

Hope that helps! Please reach out if you have additional issues

**Comment by Jhsmit** [comment]
Yes, let discuss on #349
